@baseUrl = http://localhost:3535
POST {{baseUrl}}
Content-Type: application/json

{
  "title": "Curso segunda API"
}

###

GET {{baseUrl}}/courses

###

GET {{baseUrl}}/users

###

GET {{baseUrl}}/courses?orderBy=title

###

GET {{baseUrl}}/courses/5c0a4546-2df8-4c3d-8fea-9766f1694540